apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
 namespace: kube-system
 name: local-storage
 annotations:
  storageclass.kubernetes.io/is-default-class: "true"
 labels:
  addonmanager.kubernetes.io/mode: EnsureExists
provisioner: kubernetes.io/hostpath
