apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: kube-system
  name: local-storage
  annotations:
    Storageclass.kubernetes.io/is-deafult-class: "true" 
  labels:
    addinmager.kuernetes.io/mode: EnsureExists
provisioner: kubernetes.io/hostpath
